---
- Monitoring:
    - Netdata:
        icon: netdata.png
        href: https://netdata.leojan.fr
        description: Real-time performance monitoring with 1000+ metrics

    - Glances:
        icon: glances.png
        href: http://192.168.178.13:61208
        description: System monitoring API

    - Dokploy:
        icon: docker.png
        href: https://dokploy.home.leojan.fr
        description: Docker management platform
