---
- System Metrics:
    - CPU Usage:
        icon: mdi-cpu-64-bit
        widget:
          type: glances
          url: https://glances.leojan.fr
          metric: cpu
          chart: true

    - Memory:
        icon: mdi-memory
        widget:
          type: glances
          url: https://glances.leojan.fr
          metric: memory
          chart: true

    - Network:
        icon: mdi-ethernet
        widget:
          type: glances
          url: https://glances.leojan.fr
          metric: network:eth0
          chart: true

- Monitoring:
    - Netdata:
        icon: netdata.png
        href: https://netdata.leojan.fr
        description: Real-time performance monitoring

    - Glances:
        icon: si-grafana
        href: https://glances.leojan.fr
        description: System monitoring dashboard

    - Dokploy:
        icon: docker.png
        href: https://dokploy.home.leojan.fr
        description: Container management
