---
- Monitoring:
    - Netdata:
        icon: netdata.png
        href: https://netdata.leojan.fr
        description: Real-time performance monitoring with 1000+ metrics

    - Glances:
        icon: glances.png
        href: https://glances.leojan.fr
        description: System monitoring API

    - Dokploy:
        icon: docker.png
        href: https://dokploy.home.leojan.fr
        description: Docker management platform
