---
title: Pi5 Dashboard
favicon: https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/png/raspberry-pi.png
background: https://images.unsplash.com/photo-1502790671504-542ad42d5189?auto=format&fit=crop&w=2560&q=80
cardBlur: md
theme: dark
color: slate
headerStyle: underlined
target: _self
quicklaunch:
  hideInternetSearch: true
hideVersion: true
showStats: false
layout:
  System Metrics:
    style: row
    columns: 3
  Monitoring:
    style: row
    columns: 3
  Services:
    style: row
    columns: 4
