---
- resources:
    cpu: true
    memory: true
    cputemp: true
    uptime: true
    label: Pi5

- glances:
    url: https://glances.leojan.fr
    version: 4
    metric: cpu
    chart: true
    pointsLimit: 30
    refreshInterval: 2000

- glances:
    url: https://glances.leojan.fr
    version: 4
    metric: memory
    chart: true
    pointsLimit: 30
    refreshInterval: 2000

- glances:
    url: https://glances.leojan.fr
    version: 4
    metric: disk:mmcblk0p2
    chart: true
    pointsLimit: 30
    refreshInterval: 2000

- glances:
    url: https://glances.leojan.fr
    version: 4
    metric: network:eth0
    chart: true
    pointsLimit: 30
    refreshInterval: 2000

- glances:
    url: https://glances.leojan.fr
    version: 4
    metric: sensor:cpu_thermal
    chart: true
    pointsLimit: 30
    refreshInterval: 2000

- glances:
    url: https://glances.leojan.fr
    version: 4
    metric: sensor:rp1_adc
    chart: true
    pointsLimit: 30
    refreshInterval: 2000

- glances:
    url: https://glances.leojan.fr
    version: 4
    metric: sensor:pwmfan
    chart: true
    pointsLimit: 30
    refreshInterval: 2000

- glances:
    url: https://glances.leojan.fr
    version: 4
    metric: sensor:rpi_volt
    chart: true
    pointsLimit: 30
    refreshInterval: 2000

- datetime:
    text_size: xl
    format:
      dateStyle: long
      timeStyle: short
      hour12: false
